authors:
  david:
    name: David Robert
    description: Software architect
    avatar: https://media.licdn.com/dms/image/C4E03AQFyHFjxrBVz4w/profile-displayphoto-shrink_800_800/0/1517042610662?e=1702512000&v=beta&t=sKOuix2Ia-jAmyrhr9zW5kr5cqxcnE11jvQaAbpzqbM